#vim: set ft=yml sw=2 ts=2 sts=2 et tw=78

version: '2'
services:
  db:
    image: postgres:9.5
    env_file: .postgres_env
    ports:
    - 5432:5432
  app:
    build: .
    env_file: .postgres_env
    links:
    - db:postgres
    ports:
    - 5000:5000
    environment:
    - PORT=5000
    - NODE_ENV=production
    - DB_ENV=prod
    - DB_MIGRATE=true

